### ISSUE TITLE
IllegalStateException: Report processing did not complete successfully: FAILED

### ISSUE THREAD

**Issue by nkdas** [SonarQubeCommunity/sonar-build-breaker#15] opened 2016-09-21 12:22 UTC
Hi,

Need help!
Seems like QualityGateBreaker is unable to get the Analysis ID. Need to know why.

INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 57.677s
INFO: Final Memory: 48M/430M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Report processing did not complete successfully: FAILED
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:152)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:108)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.executeOn(QualityGateBreaker.java:95)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
	at org.sonarsource.scanner.cli.Main.main(Main.java:60)
Build step 'Execute SonarQube Scanner' marked build as failure

**Comment by mjdetullio** [comment] 2016-09-21 14:39
Duplicate of #14

**Closed by mjdetullio** 2016-09-21 14:39 UTC
