### ISSUE TITLE
Plugin breaks analysis on server error

### ISSUE THREAD

**Issue by rgcosma** [SonarQubeCommunity/sonar-build-breaker#18] opened 2016-11-09 12:06 UTC
Seems polling the Sonar API does not tolerate slow response or temporary network failures, because randomly I get this error
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project test: Protocol message end-group tag did not match expected tag
```
Re-triggering the same job does work, said error pops quite randomly. If the communication steps are still the ones described in http://www.sonarqube.org/why-you-shouldnt-use-build-breaker/ maybe an additional retry-on-server-error parameter would help?

**Comment by mjdetullio** [comment] 2017-04-08 04:07
Duplicate of #12

**Closed by mjdetullio** 2017-04-08 04:07 UTC
